export const ALL_REVIEWS_MOCK = [
  {
    id: 2,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 3,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 4,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 5,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 6,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 7,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 8,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 9,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 10,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 11,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 12,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 13,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 14,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 15,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 16,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 17,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 18,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 19,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 20,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 21,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 22,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 23,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 24,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 25,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 26,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 27,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 28,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 29,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 30,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 31,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 32,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 33,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 34,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 35,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 36,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 37,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 38,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 39,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 40,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 41,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 42,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 43,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 44,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 45,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 46,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 47,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
  {
    id: 48,
    comments: [
      {
        commentId: 1,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Отличный продукт!",
        reviewDate: new Date("2024-02-28"),
      },
      {
        commentId: 2,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Очень доволен качеством.",
        reviewDate: new Date("2024-02-29"),
      },
      {
        commentId: 3,
        userName: "User1",
        userAvatar: "avatar1.jpg",
        comment: "Быстрая доставка.",
        reviewDate: new Date("2024-02-30"),
      },
    ],
  },
];
