export const ALL_REVIEWS_MOCK = [
  {
    id: 1,
    userName: "User1",
    userAvatar: "avatar1.jpg",
    reviews: [
      "Отличный продукт!",
      "Очень доволен качеством.",
      "Быстрая доставка.",
    ],
    reviewDate: new Date("2024-02-29"),
  },
  {
    id: 2,
    userName: "User2",
    userAvatar: "avatar2.jpg",
    reviews: [
      "Прекрасный товар.",
      "Очень понравилось качество.",
      "Рекомендую всем!",
    ],
    reviewDate: new Date("2024-02-28"),
  },
  {
    id: 3,
    userName: "User3",
    userAvatar: "avatar3.jpg",
    reviews: [
      "Замечательное качество!",
      "Быстрая доставка.",
      "Продукт полностью соответствует описанию.",
    ],
    reviewDate: new Date("2024-02-27"),
  },
  {
    id: 4,
    userName: "User4",
    userAvatar: "avatar4.jpg",
    reviews: [
      "Очень доволен покупкой.",
      "Отличное качество товара.",
      "Рекомендую магазин всем!",
    ],
    reviewDate: new Date("2024-02-26"),
  },
  {
    id: 5,
    userName: "User5",
    userAvatar: "avatar5.jpg",
    reviews: [
      "Спасибо за отличный товар!",
      "Продукт превзошел мои ожидания.",
      "Очень быстрая доставка!",
    ],
    reviewDate: new Date("2024-02-25"),
  },
  {
    id: 6,
    userName: "User6",
    userAvatar: "avatar6.jpg",
    reviews: [
      "Продукт соответствует описанию.",
      "Быстрая доставка.",
      "Очень доволен покупкой.",
    ],
    reviewDate: new Date("2024-02-24"),
  },
  {
    id: 7,
    userName: "User7",
    userAvatar: "avatar7.jpg",
    reviews: [
      "Быстрая доставка, все отлично упаковано.",
      "Прекрасное качество товара.",
      "Рекомендую магазин.",
    ],
    reviewDate: new Date("2024-02-23"),
  },
  {
    id: 8,
    userName: "User8",
    userAvatar: "avatar8.jpg",
    reviews: [
      "Отличное обслуживание клиентов.",
      "Спасибо за быструю доставку.",
      "Продукт пришел в целости и сохранности.",
    ],
    reviewDate: new Date("2024-02-22"),
  },
  {
    id: 9,
    userName: "User9",
    userAvatar: "avatar9.jpg",
    reviews: [
      "Надежный магазин, всегда заказываю здесь.",
      "Продукция соответствует фото на сайте.",
      "Очень доволен качеством.",
    ],
    reviewDate: new Date("2024-02-21"),
  },
  {
    id: 10,
    userName: "User10",
    userAvatar: "avatar10.jpg",
    reviews: [
      "Отличное соотношение цены и качества.",
      "Быстрая доставка.",
      "Продукт оправдал ожидания.",
    ],
    reviewDate: new Date("2024-02-20"),
  },
  {
    id: 11,
    userName: "User11",
    userAvatar: "avatar11.jpg",
    reviews: [
      "Продукт превзошел мои ожидания.",
      "Отличный сервис.",
      "Рекомендую всем друзьям!",
    ],
    reviewDate: new Date("2024-02-19"),
  },
  {
    id: 12,
    userName: "User12",
    userAvatar: "avatar12.jpg",
    reviews: [
      "Отличный выбор, рекомендую всем!",
      "Быстрая доставка.",
      "Очень доволен качеством.",
    ],
    reviewDate: new Date("2024-02-18"),
  },
  {
    id: 13,
    userName: "User13",
    userAvatar: "avatar13.jpg",
    reviews: [
      "Супер! Спасибо за быструю доставку.",
      "Продукция соответствует фото.",
      "Отличное качество!",
    ],
    reviewDate: new Date("2024-02-17"),
  },
  {
    id: 14,
    userName: "User14",
    userAvatar: "avatar14.jpg",
    reviews: [
      "Очень хороший сервис.",
      "Быстрая доставка.",
      "Отличное качество!",
    ],
    reviewDate: new Date("2024-02-16"),
  },
  {
    id: 15,
    userName: "User15",
    userAvatar: "avatar15.jpg",
    reviews: [
      "Впечатляющее качество товара.",
      "Продукция соответствует описанию.",
      "Быстрая доставка.",
    ],
    reviewDate: new Date("2024-02-15"),
  },
  {
    id: 16,
    userName: "User16",
    userAvatar: "avatar16.jpg",
    reviews: [
      "Продукт соответствует описанию.",
      "Быстрая доставка.",
      "Очень доволен покупкой.",
    ],
    reviewDate: new Date("2024-02-14"),
  },
  {
    id: 17,
    userName: "User17",
    userAvatar: "avatar17.jpg",
    reviews: [
      "Заказывал товар, но получил бракованный.",
      "Доставка задержалась.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-02-13"),
  },
  {
    id: 18,
    userName: "User18",
    userAvatar: "avatar18.jpg",
    reviews: [
      "Отличное обслуживание клиентов.",
      "Быстрая доставка, все отлично упаковано.",
      "Продукт пришел в целости и сохранности.",
    ],
    reviewDate: new Date("2024-02-12"),
  },
  {
    id: 19,
    userName: "User19",
    userAvatar: "avatar19.jpg",
    reviews: [
      "Недоволен качеством товара.",
      "Долгая доставка.",
      "Плохая связь с клиентами.",
    ],
    reviewDate: new Date("2024-02-11"),
  },
  {
    id: 20,
    userName: "User20",
    userAvatar: "avatar20.jpg",
    reviews: [
      "Отличное соотношение цены и качества.",
      "Быстрая доставка.",
      "Продукт оправдал ожидания.",
    ],
    reviewDate: new Date("2024-02-10"),
  },
  {
    id: 21,
    userName: "User21",
    userAvatar: "avatar21.jpg",
    reviews: [
      "Продукт превзошел мои ожидания.",
      "Отличный сервис.",
      "Рекомендую всем друзьям!",
    ],
    reviewDate: new Date("2024-02-09"),
  },
  {
    id: 22,
    userName: "User22",
    userAvatar: "avatar22.jpg",
    reviews: [
      "Продукт не соответствует описанию.",
      "Плохое качество товара.",
      "Очень долго ждал доставку.",
    ],
    reviewDate: new Date("2024-02-08"),
  },
  {
    id: 23,
    userName: "User23",
    userAvatar: "avatar23.jpg",
    reviews: [
      "Замечательное качество товара!",
      "Доставка задержалась из-за погодных условий.",
      "Небольшие проблемы с упаковкой.",
    ],
    reviewDate: new Date("2024-02-07"),
  },
  {
    id: 24,
    userName: "User24",
    userAvatar: "avatar24.jpg",
    reviews: [
      "Продукт оказался сломанным.",
      "Долгая доставка.",
      "Не доволен обслуживанием клиентов.",
    ],
    reviewDate: new Date("2024-02-06"),
  },
  {
    id: 25,
    userName: "User25",
    userAvatar: "avatar25.jpg",
    reviews: [
      "Спасибо за отличный товар!",
      "Продукт превзошел мои ожидания.",
      "Очень быстрая доставка!",
    ],
    reviewDate: new Date("2024-02-05"),
  },
  {
    id: 26,
    userName: "User26",
    userAvatar: "avatar26.jpg",
    reviews: [
      "Продукт оказался выше моих ожиданий!",
      "Отличный сервис.",
      "Спасибо за быструю доставку!",
    ],
    reviewDate: new Date("2024-02-04"),
  },
  {
    id: 27,
    userName: "User27",
    userAvatar: "avatar27.jpg",
    reviews: [
      "Получил товар вовремя, но упаковка была повреждена.",
      "Качество товара не очень.",
      "Неудовлетворен обслуживанием клиентов.",
    ],
    reviewDate: new Date("2024-02-03"),
  },
  {
    id: 28,
    userName: "User28",
    userAvatar: "avatar28.jpg",
    reviews: [
      "Быстро сработали с заказом, спасибо!",
      "Продукция соответствует описанию.",
      "Буду заказывать снова.",
    ],
    reviewDate: new Date("2024-02-02"),
  },
  {
    id: 29,
    userName: "User29",
    userAvatar: "avatar29.jpg",
    reviews: [
      "Продукт оказался не таким, как на картинке.",
      "Доставка опоздала на несколько дней.",
      "Неудовлетворен качеством.",
    ],
    reviewDate: new Date("2024-02-01"),
  },
  {
    id: 30,
    userName: "User30",
    userAvatar: "avatar30.jpg",
    reviews: [
      "Заказывал товар, но получил другой.",
      "Быстрая доставка, но товар оказался сломанным.",
      "Не рекомендую этот магазин.",
    ],
    reviewDate: new Date("2024-01-31"),
  },
  {
    id: 31,
    userName: "User31",
    userAvatar: "avatar31.jpg",
    reviews: [
      "Продукт оказался низкого качества.",
      "Долгая доставка.",
      "Не рекомендую.",
    ],
    reviewDate: new Date("2024-01-30"),
  },
  {
    id: 32,
    userName: "User32",
    userAvatar: "avatar32.jpg",
    reviews: [
      "Неудовлетворен качеством товара.",
      "Доставка заняла слишком много времени.",
      "Обслуживание клиентов неэффективное.",
    ],
    reviewDate: new Date("2024-01-29"),
  },
  {
    id: 33,
    userName: "User33",
    userAvatar: "avatar33.jpg",
    reviews: [
      "Продукция не соответствует описанию.",
      "Плохое качество товара.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-28"),
  },
  {
    id: 34,
    userName: "User34",
    userAvatar: "avatar34.jpg",
    reviews: [
      "Очень плохой опыт покупки.",
      "Доставка опоздала на несколько дней.",
      "Не рекомендую этот магазин.",
    ],
    reviewDate: new Date("2024-01-27"),
  },
  {
    id: 35,
    userName: "User35",
    userAvatar: "avatar35.jpg",
    reviews: [
      "Отличное соотношение цены и качества.",
      "Продукция полностью соответствует описанию.",
      "Быстрая доставка.",
    ],
    reviewDate: new Date("2024-01-26"),
  },
  {
    id: 36,
    userName: "User36",
    userAvatar: "avatar36.jpg",
    reviews: [
      "Продукт не соответствует описанию.",
      "Долгая доставка.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-25"),
  },
  {
    id: 37,
    userName: "User37",
    userAvatar: "avatar37.jpg",
    reviews: [
      "Отличное обслуживание клиентов.",
      "Быстрая доставка, все отлично упаковано.",
      "Продукт пришел в целости и сохранности.",
    ],
    reviewDate: new Date("2024-01-24"),
  },
  {
    id: 38,
    userName: "User38",
    userAvatar: "avatar38.jpg",
    reviews: [
      "Недоволен качеством товара.",
      "Доставка заняла слишком много времени.",
      "Не рекомендую этот магазин.",
    ],
    reviewDate: new Date("2024-01-23"),
  },
  {
    id: 39,
    userName: "User39",
    userAvatar: "avatar39.jpg",
    reviews: [
      "Продукция не соответствует описанию.",
      "Плохое качество товара.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-22"),
  },
  {
    id: 40,
    userName: "User40",
    userAvatar: "avatar40.jpg",
    reviews: [
      "Быстрая доставка, но товар оказался сломанным.",
      "Отличное качество товара.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-21"),
  },
  {
    id: 41,
    userName: "User41",
    userAvatar: "avatar41.jpg",
    reviews: [
      "Отличное обслуживание клиентов.",
      "Спасибо за быструю доставку.",
      "Продукт пришел в целости и сохранности.",
    ],
    reviewDate: new Date("2024-01-20"),
  },
  {
    id: 42,
    userName: "User42",
    userAvatar: "avatar42.jpg",
    reviews: [
      "Продукт оказался ниже ожиданий.",
      "Долгая доставка.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-19"),
  },
  {
    id: 43,
    userName: "User43",
    userAvatar: "avatar43.jpg",
    reviews: [
      "Недоволен качеством товара.",
      "Доставка заняла слишком много времени.",
      "Не рекомендую этот магазин.",
    ],
    reviewDate: new Date("2024-01-18"),
  },
  {
    id: 44,
    userName: "User44",
    userAvatar: "avatar44.jpg",
    reviews: [
      "Продукция не соответствует описанию.",
      "Плохое качество товара.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-17"),
  },
  {
    id: 45,
    userName: "User45",
    userAvatar: "avatar45.jpg",
    reviews: [
      "Быстрая доставка, но товар оказался сломанным.",
      "Отличное качество товара.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-16"),
  },
  {
    id: 46,
    userName: "User46",
    userAvatar: "avatar46.jpg",
    reviews: [
      "Отличное обслуживание клиентов.",
      "Спасибо за быструю доставку.",
      "Продукт пришел в целости и сохранности.",
    ],
    reviewDate: new Date("2024-01-15"),
  },
  {
    id: 47,
    userName: "User47",
    userAvatar: "avatar47.jpg",
    reviews: [
      "Продукт оказался ниже ожиданий.",
      "Долгая доставка.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-14"),
  },
  {
    id: 48,
    userName: "User48",
    userAvatar: "avatar47.jpg",
    reviews: [
      "Продукт оказался ниже ожиданий.",
      "Долгая доставка.",
      "Не рекомендую магазин.",
    ],
    reviewDate: new Date("2024-01-14"),
  },
];
